import type { Metadata } from "next";

import { DemoFormClient } from "../../components/demo-form-client";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Demo — Runtime Walkthrough",
  description:
    "Step through the OpenSphinx runtime loop live: seed steps, adaptive follow-up, and completion explained as you go."
};

export default function DemoPage() {
  const hasOpenAiKey = Boolean(process.env.OPENAI_API_KEY?.trim());

  return (
    <main className="demo-page site-container">
      <div className="demo-page__intro">
        <span className="eyebrow">Runtime walkthrough</span>
        <h1>See what happens at every step</h1>
        <p>
          This route runs the full OpenSphinx loop: <code>FormConfig</code> on
          the server, <code>generateStep(session)</code> returning each step,
          and <code>SphinxForm</code> rendering the result. The inspector panel
          on the right explains what the engine did and why.
        </p>
      </div>

      <div className="demo-page__grid">
        <div className="demo-page__frame">
          <DemoFormClient showOpenAiKeyHint={!hasOpenAiKey} />
        </div>

        <div className="demo-page__side">
          <section className="demo-sidecard docs-card">
            <h2>The runtime loop</h2>
            <ol className="demo-sidecard__steps">
              <li>
                <strong>SessionState</strong> tracks config, answer history,
                pending steps, and completed step count.
              </li>
              <li>
                The server calls <code>generateStep(session)</code> and returns
                either a new <code>Step</code> or <code>complete</code>.
              </li>
              <li>
                <code>SphinxForm</code> renders the step, collects answers, and
                updates session state for the next request.
              </li>
            </ol>
          </section>

          <section className="demo-sidecard docs-card">
            <h2>Step origins</h2>
            <ul>
              <li>
                <strong>Seed</strong> &mdash; deterministic opening steps
                defined in <code>FormConfig.seedSteps</code>.
              </li>
              <li>
                <strong>Model</strong> &mdash; adaptive follow-up generated by
                the AI model based on session history.
              </li>
              <li>
                <strong>Fallback</strong> &mdash; safe placeholder questions
                when no model is configured or generation fails.
              </li>
            </ul>
          </section>

          <section className="demo-sidecard docs-card">
            <h2>Current mode</h2>
            <p>
              {hasOpenAiKey ? (
                <>
                  An <code>OPENAI_API_KEY</code> is set, so the engine uses a
                  real model for adaptive follow-up after the seed steps.
                </>
              ) : (
                <>
                  No <code>OPENAI_API_KEY</code> is configured. The engine
                  demonstrates the full loop using seed steps and safe fallback
                  behavior &mdash; no API calls leave your server.
                </>
              )}
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
